<?php
/**
 * MagePal Google Tag Manager for Magento 1
 *
 * Copyright © 2016 MagePal. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<!-- Google Data Layer by MagePal-->
<script>
window.dataLayer = window.dataLayer || [];
<?php /** @var $this MagePal_GoogleTagManager_Block_Tm **/ ?>
<?php echo $this->getGtmTrackingCode(); ?>
<?php echo $this->getOrdersTrackingCode(); ?>
</script>
<!-- Google Data Layer by MagePal-->